apiVersion: v1
kind: Service
metadata:
  name: pext
spec:
  selector:
    app: hello-python
  ports:
  - protocol: "TCP"
    port: 5000
    targetPort: 5000
  type: LoadBalancer

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: personal_expense_tracker
spec:
  selector:
    matchLabels:
      app: personal_expense_tracker
  replicas: 1
  template:
    metadata:
      labels:
        app: personal_expense_tracker
    spec:
      containers:
      - name: pext
        image: pext:1.0
        imagePullPolicy: Never
        ports:
        - containerPort: 5000