# Generated by Django 4.1.2 on 2022-10-21 14:34

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Budget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Budget Name', max_length=255, verbose_name='Budget Name')),
                ('amount', models.IntegerField(help_text='Budget Amount', verbose_name='Bugdget Amount')),
            ],
            options={
                'verbose_name': 'Budget',
                'verbose_name_plural': 'Budgets',
            },
        ),
        migrations.CreateModel(
            name='Wallet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Wallet Name', max_length=255, verbose_name='Wallet Name')),
                ('is_active', models.BooleanField(default=True)),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='expense_tracker.wallet')),
            ],
            options={
                'verbose_name': 'Wallet',
                'verbose_name_plural': 'Wallets',
            },
        ),
        migrations.CreateModel(
            name='Income',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Income Name', max_length=255, verbose_name='Income Name')),
                ('amount', models.IntegerField(help_text='Income Amount', verbose_name='Income Amount')),
                ('income_budget', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='expense_tracker.budget')),
                ('income_wallet', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='expense_tracker.wallet')),
            ],
            options={
                'verbose_name': 'Income',
                'verbose_name_plural': 'Incomes',
            },
        ),
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Expense Name', max_length=255, verbose_name='Expense Name')),
                ('amount', models.IntegerField(help_text='Expense Amount', verbose_name='Expense Amount')),
                ('expense_budget', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='expense_tracker.budget')),
                ('expense_wallet', models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='expense_tracker.wallet')),
            ],
            options={
                'verbose_name': 'Expense',
                'verbose_name_plural': 'Expenses',
            },
        ),
        migrations.AddField(
            model_name='budget',
            name='expense_wallet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.RESTRICT, to='expense_tracker.wallet'),
        ),
    ]
